### PR TITLE
Added the 'run-ck' executable

### PR DESCRIPTION
**Pull request by effectfully**
Lucas asked for a more convenient way to run programs using the CK machine.

### CODE REVIEW

**Comment by michaelpj** [comment]
Nice! Personally, I'd probably prefer a non-interactive version by default - is there much use for running several subsequently in the same session?

**Comment by effectfully** [comment]
I think interactive is more convenient and doesn't sacrifice anything, but thanks, I'll ask Lucas whether non-interactive would be more convenient for him.

**Comment by michaelpj** [comment]
I guess I just see myself feeding stuff into it from other scripts.

**Comment by effectfully** [comment]
I asked Lucas, he's fine with both options. Personally, I prefer the interactive version.
@michaelpj, do you plan to use the evaluator? If so, I'll add a flag, so the executable is convenient for all of us.

**Comment by michaelpj** [comment]
I'd definitely like to use the evaluator. It would be nice e.g. when testing generated PLC terms to be able to quickly evaluate them and check the result made sense. Of course, I could do this in Haskell, but having an executable would be nice too. But I envisage mostly feeding it files.

**Comment by effectfully** [comment]
Ok. Do you prefer feeding it file names or file contents?

I'm merging this just not to make Lucas wait. I'll change the executable in a separate pull request.

**Comment by michaelpj** [comment]
Files are fine - I can always use shell substitutions to put the output of something else into a file. If you wanted to make it also accept stdin that would be nice but not really needed.

**Pull request merged**
