### PR TITLE
TypeSynthesis: get rid of the non-exhaustive pattern match in a slightly better way

### PR DESCRIPTION
**Pull request by michaelpj**
The action is in the second commit. We already have `InternalError` to signal "programmer error", so use that.

### CODE REVIEW

**Comment by vmchale** [comment]
Why? This seems less than ideal and inefficient.

**Comment by vmchale** [comment]
Once Roman's patch to the standard library lands, this will be fairly easy: https://iohk.myjetbrains.com/youtrack/issue/CGP-279

**Comment by michaelpj** [comment]
How will Roman's patch make it easier? I don't in fact see how it helps at all?

I don't think this is inefficient - it does one extra traversal of these small terms (which is approximately the same amount of work that it's doing to build them in the first place). We have code to generate an un-annotated term, and code to annotate it - this does the obvious thing of just sticking them together, rather than making an ad-hoc fusion of the two.

**Comment by michaelpj** [comment]
I added a message to the error. Possibly it should be an exception, given that in other places we use exceptions to signal "programmer error", but we can change that later.

**Comment by michaelpj** [comment]
ping

**Comment by michaelpj** [comment]
This is obsolete regardless.

**Pull request closed without merging**
