### PR TITLE
[WIP] fix CGP-276

### PR DESCRIPTION
**Pull request by vmchale**
This is a partial fix to the normalization bug report, using Michael's test case.

### CODE REVIEW

**Comment by vmchale** [comment]
This still needs some polish on the public API

**Comment by michaelpj** [comment]
Isn't this a little premature given that we're going to be discussing how to put reduction into the spec at the meeting today?

**Comment by michaelpj** [comment]
(I realise that's rich considering I did the same thing, but that *was* premature :P )

**Comment by vmchale** [comment]
Perhaps? I am quite confused about the status of this due to the bug report but also edits to the spec. I will ask today in meeting.

I can add a "no merge" tag.

**Pull request closed without merging**
