### PR TITLE
fix type-checker scoping issues

### PR DESCRIPTION
**Pull request by vmchale**
This fixes the bug in the typechecker. Among other things, this means that we will no longer need `Quote` while substituting

### CODE REVIEW

**Comment by michaelpj** [comment]
I don't think we should do just this alone. If we're switching to not needing global uniqueness that has a bunch of consequences like maybe meaning we don't need the renamer etc. If we just change one bit of the typechecker it's going to be unclear what our assumptions are!

I think we should finish https://github.com/input-output-hk/plutus-prototype/pull/110 and then come back to this as it's a bigger issue.

(Also, I'm not sure it's accurate to describe this as a "fix", it's more of a fundamental change to how we handle variables in the typechecker!)

**Comment by vmchale** [comment]
It's a fix in that it fixes `head` and `tail` and thus obviates the need for https://github.com/input-output-hk/plutus-prototype/pull/110

It's pretty small so while it is a big change to behavior, it's relatively simple code.

I'm pretty sure we still need the renamer, just not for testing the typechecker.

**Comment by michaelpj** [comment]
Sure it's simple code, but it's absolutely not simple in terms of the implications for the rest of the codebase. It's already a headache keeping it straight where we're assuming global uniqueness and where we're not - after this change I actually have no idea whether the typechecker needs it or not.

IMO https://github.com/input-output-hk/plutus-prototype/pull/110 is much simpler because it fixes the problem without signficantly changing our approach.

**Comment by vmchale** [comment]
After this, the typechecker allows name shadowing and does not require uniqueness anywhere. That is unfortunately not reflected in the test suite.

And regardless of whether it's simpler than https://github.com/input-output-hk/plutus-prototype/pull/110, it is more performant and makes using a type environment easier; thus I think it will supersede the other approach.

**Comment by michaelpj** [comment]
Potential performance improvements are waaaay less important than comprehensibility at this stage, IMO. This may well supersede the current approach in the long run, but I don't think it's appropriate as bug fix - this should be a major design change with a bunch of tests, and a careful piece of argument about why it does the right thing and fits with the overall approach. For now, let's just do the simple fix.

Additionally, I don't think this is sufficient to make the type-checker handle shadowing. It handles it while substituting, but not while generally traversing binders. If we have two nested binders that bind the same name (no substitution involved!) we will erroneously think that references to the two variables are the same type. (I wouldn't waste time trying to fix that now - I think the right thing to do would be to rewrite the typechecker to use environments thoroughly)

**Comment by vmchale** [comment]
> If we have two nested binders that bind the same name (no substitution involved!) we will erroneously think that references to the two variables are the same type.

I'm not clear on what this means. Do you have an example?

**Comment by michaelpj** [comment]
Consider something like:
```
(abs a (type)
  -- the outer `a` is used here
  (lam arg a
    -- the vey same `a`! this should be fine if we're allowing shadowing
    (abs a (type)
      -- the inner `a` is used here
      (lam f (fun a a)
        -- Should be a type error: `f : innerA -> innerA`, `arg : outerA`.
        -- But we're representing the inner and the outer `a` with the same name,
        -- so we'll just have `f : a -> a`, `arg : a` which looks fine.
        [ f arg ]
      )
    )
  )
)
```
Initially I thought I might not be able to get an example that would be produced by parsing, but I'm pretty sure this would give the wrong answer.

And of course things become trickier if we have terms that are constructed programmatically, where there might be references to the "outer" `a` inside the "inner" `a`'s scope. Maybe we want to ban that - but then we're back to having subtle invariants. Where are those documented? Have we got a good argument that they're sufficient?

Anyway, my point is mainly that this is a very subtle change and deserves serious consideration.

**Comment by vmchale** [comment]
That example fails to typecheck with an error message. I've added it as a test case.

**Comment by vmchale** [comment]
Ah okay, thanks. I've added a new unit test. 

They currently break because I just use the `==` instance for typechecking. I'm not sure if we want to use something else in the typechecker which is scope-dependent (which seems sensible to me), or just document to run `annotateProgram` beforehand.

**Comment by michaelpj** [comment]
I don't think `annotateProgram` is going to help, unless I'm missing something? Do you mean `rename`? But then we're back to requiring global uniqueness. At that point this has no advantages over the other PR, and puts us in a weird state.

I don't really understand why you're so opposed to just finishing https://github.com/input-output-hk/plutus-prototype/pull/110 for now. It's the right fix given our current approach to variable names, and I think it's possible that we'll want to move to an environment-based approach, but there's no need to couple that (big, subtle) change to the bug fix.

**Comment by vmchale** [comment]
Yes, you're right, `rename`.

It's useful over the other PR mainly because it avoids pulling in the `Quote` monad (which is unwieldy), and because it's more efficient (i.e. secure and actually useful) and amenable to using type environments (the approach we want, because that is the secure approach).

**Comment by michaelpj** [comment]
The current approach just *is* unwieldy, because it has to care about variable freshness.

I do agree that an environment-based approach is better, but we shouldn't do it half-heartedly! The modest amount of code in https://github.com/input-output-hk/plutus-prototype/pull/110 seems vastly preferable to having our codebase in an inconsistent state wrt the implicit invariants, which are already the hardest thing to reason about.

**Comment by michaelpj** [comment]
Maybe it does, maybe it doesn't. The other one makes substitution work the way it normally works, making the normal adjustment to bound variables. This one does... something else. Is it correct? Hard to say. Better IMO to do the one that's obviously right and then move to this when we do everything with environments.

**Pull request closed without merging**
