### PR TITLE
conform to spec update

### PR DESCRIPTION
**Pull request by vmchale**
This ensures type synthesis conforms to the latest spec.

### CODE REVIEW

**Comment by michaelpj** [comment]
Please can we have some tests? At least the ones I added in https://github.com/input-output-hk/plutus-prototype/pull/78. I don't think this will in fact handle any cases with redexes, since it doesn't do any reduction (I commented on the thread with Rebecca).

**Comment by michaelpj** [comment]
Specifically these tests should work: https://github.com/input-output-hk/plutus-prototype/pull/78/commits/2febe98a9e3423785b6994713e2ed2a7eaeb180c

**Comment by vmchale** [comment]
Are those now valid according to the spec? I am confused as to where it diverges.

**Comment by michaelpj** [comment]
Indeed they aren't - but given that the point was supporting redexes everywhere, those tests not working is a clue that the spec update isn't quite right (see my recent email).

**Comment by michaelpj** [comment]
Perhaps we are talking at cross purposes here: I would like us to make a change that demonstrably fixes the problem, hence the tests. If they fail, well then, that's another reason not to merge this while we sort out the spec. But I would like us to *notice* that this didn't have the effect that we were expecting it to.

I would also generally expect any change like this to have at least one test demonstrating the change in behaviour.

**Pull request closed without merging**
