### PR TITLE
Preparations for merging the CEK machine in

### PR DESCRIPTION
**Pull request by effectfully**
Added the 'Evaluation' folder, moved the CK machine there, abstracted 'MachineException' and 'EvaluationResult'

### CODE REVIEW

**Comment by effectfully** [comment]
@disassembler, @iohk-devops, @michaelpj, something wrong with the build again?

**Comment by michaelpj** [comment]
No, the builds are just queued. It *did* take a while to get to that point, and it *does* fail to update the status when the build is queued, which it could.

**Comment by michaelpj** [comment]
https://hydra.iohk.io/jobset/serokell/plutus-pr-99

**Comment by michaelpj** [comment]
Or indeed something might be wrong, since I wouldn't expect them to be queued for this long.

**Comment by michaelpj** [comment]
It finished, but hlint failed.

**Pull request merged**
