### PR TITLE
Remove imprecise errors

### PR DESCRIPTION
**Pull request by vmchale**
Remove imprecise errors.

### CODE REVIEW

**Comment by michaelpj** [comment]
It would be nice to offer some reasoning :)

Here's mine for adding it: `Error` is the top-level error type that we expose, often with a `MonadError Error m` constraint. This is nice, but if you want to keep operating in that monad afterwards and throw your own errors, the type is wrong. So you can stop the world, map everything up, and start again, but that's annoying.

**Comment by michaelpj** [comment]
... so it's helpful to have somewhere to stuff additional errors.

**Comment by vmchale** [comment]
You can still catch errors, no? 

The reasoning behind removing it is that I would prefer to have a structured type exposed to users of `language-plutus-core`. If a program fails with `OtherError` that's not particularly user-friendly. Parsing error messages or even just comparing strings would be unfortunate.

**Comment by vmchale** [comment]
Sounds good.

Could we add another error type for conversions and make that part of `Error`? Even if GHC gives stringly-typed errors somewhere, it would still be nice to have a `PluginError` or the like.

**Comment by michaelpj** [comment]
We could - but `language-plutus-core` doesn't know about the existence of the plugin, so I'd prefer it didn't appear in the possible error types!

Here's a third suggestion, which I kind of like:
```haskell
class Is a b whre
    embed :: a -> b

-- get type signatures like this
parseProgram :: (MonadError b m, Is (Error AlexPosn) b) => BSL.ByteString -> QuoteT m (Program TyName Name AlexPosn)
```

That way what you're saying is "you can run this in any error handling monad you like, provided you give me a way of turning my errors into yours". I think this also would subsume the existing `IsError` class which is doing a very similar thing. Thoughts?

**Comment by vmchale** [comment]
Seems like a big hammer but there's nothing inherently bad about it. Also, I'm afraid I don't see how it fixes the problem you mentioned before.

**Comment by michaelpj** [comment]
Yes, it is a biggish hammer. The payoff from using the typeclass rather than passing a function is that you don't have to pass anything if it's id!

The way it solves the problem is that the plugin can define it's own error type, and an embedding of Error into it, and then it can use the functions without language-plutus-core needing to know about its error type.

**Comment by michaelpj** [comment]
I'll open a PR.

**Comment by vmchale** [comment]
Sounds good.

**Pull request merged**
