### PR TITLE
fix renamer

### PR DESCRIPTION
**Pull request by vmchale**
This fixes the renamer and adds a test.

It is based on @michaelpj's pull request.

### CODE REVIEW

**Comment by michaelpj** [comment]
I'd just call it a basic wrapping test - it's not especially related to that ticket.

Also, not a big deal but you can cherry pick commits from my branch and it'll do the right thing when merging.

**Comment by vmchale** [comment]
Oh good point.

**Comment by michaelpj** [comment]
So you didn't rename the test case?

**Comment by vmchale** [comment]
Oh, nope. It turned out that it's not a bug. I could rename to `wrapTest` if you want?

**Comment by michaelpj** [comment]
Yeah I just think it's misleading to link it to the ticket.

**Pull request merged**
