### PR TITLE
[DEVOPS-1021] Adding stylish/hlint to CI

### PR DESCRIPTION
**Pull request by disassembler**
https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-1021

### CODE REVIEW

**Comment by michaelpj** [comment]
The stylish haskell check also fails, but claims there is no log available.

**Comment by michaelpj** [comment]
Building the stylish haskell check directly, I have the following failures:
```
Language.Haskell.Stylish.Parse.parseModule: could not parse ./language-plutus-core/dist/build/Language/PlutusCore/Lexer.hs: ParseFailed (SrcLoc "<unknown>.hs" 1488 3) "Parse error: indexInt16OffAddr#"
Language.Haskell.Stylish.Parse.parseModule: could not parse ./language-plutus-core/dist/build/Language/PlutusCore/Parser.hs: ParseFailed (SrcLoc "<unknown>.hs" 3 1) "Parse error: #"
Language.Haskell.Stylish.Parse.parseModule: could not parse ./language-plutus-core/.stack-work/dist/x86_64-linux-nix/Cabal-2.0.1.0/build/Language/PlutusCore/Lexer.hs: ParseFailed (SrcLoc "<unknown>.hs" 1460 3) "Parse error: indexInt16OffAddr#"
Language.Haskell.Stylish.Parse.parseModule: could not parse ./language-plutus-core/.stack-work/dist/x86_64-linux-nix/Cabal-2.0.1.0/build/Language/PlutusCore/Parser.hs: ParseFailed (SrcLoc "<unknown>.hs" 3 1) "Parse error: #"
Language.Haskell.Stylish.Parse.parseModule: could not parse ./docs/model/UTxO.hsproj/Witness.hs: ParseFailed (SrcLoc "<unknown>.hs" 60 9) "Parse error: |"
Language.Haskell.Stylish.Parse.parseModule: could not parse ./docs/model/UTxO.hsproj/Examples/Simple.hs: ParseFailed (SrcLoc "<unknown>.hs" 46 63) "Parse error: |"
*** Stylish-haskell found changes that need addressed first
*** Please run `nix-shell -A fixStylishHaskell` and commit changes
*** or apply the diff generated by hydra if you don't have nix.
```

**Comment by effectfully** [comment]
`- error: {lhs: "do { x <- y ; pure (f x) }", rhs: "f =<< y", name: "Avoid do-notation"}`

Will this reformat

```do
    x <- y
    pure (f x)```

into `f =<< y`? If yes, I do not like it. `y` and `f` can be big expressions and we'll get 160 symbols again. There is nothing wrong with `do { x <- y ; pure (f x) }`. Also why `f =<< y` and not `y >>= f`?

`- error: {lhs: "concatMap", rhs: "(=<<)", name: "Generalize concatMap"}`

No.

`- error: {lhs: "f >> pure ()", rhs: "void f", name: "Use void"}`

If this reformats

```do
    g
    f
    pure ()```

into

```do
    g
    void f```

then no.

**Comment by effectfully** [comment]
`stylish-haskell` has no haddocks and I can't find any documentation. @vmchale, please specify for each `stylish-haskell` rule what it's responsible for.

**Comment by vmchale** [comment]
@effectfully I've fixed the `hlint` rules.

@michaelpj `true` and `false` seem to be the exact same thing, so I think that `hlint` is correct in this case.

**Comment by michaelpj** [comment]
Yes, that's a bug. Please don't delete it, I'll fix it.

**Comment by vmchale** [comment]
Ah okay. I'll revert that one.

**Comment by vmchale** [comment]
@michaelpj I think it should be ready to merge once you fix the duplication in `test/Quotation/Spec.hs`.

**Comment by vmchale** [comment]
@disassembler any clue why the CI for `stylish-haskell`/`hlint` isn't showing? Is it just delayed?

**Comment by michaelpj** [comment]
The jobs are just queued: https://hydra.iohk.io/eval/289521

**Comment by michaelpj** [comment]
I'll merge this once they get through.

**Comment by michaelpj** [comment]
Hm, the stylish check failed, and the diff it produced is crazy - it basically deletes `PlutusPrelude`. Any ideas?

**Comment by michaelpj** [comment]
```
stylish-haskell: ./language-plutus-core/prelude/PlutusPrelude.hs: commitBuffer: invalid argument (invalid character)
stylish-haskell: ./language-plutus-core/src/Language/PlutusCore/Name.hs: commitBuffer: invalid argument (invalid character)
```

appears in the logs. I guess maybe that means the diff it produces isn't going to be good, I guess I can fix it by hand.

**Pull request merged**
